### ISSUE TITLE
Issue while loading the export.pkl file

### ISSUE THREAD

**Issue by DhanyaRaghu95** [pankymathur/Fine-Grained-Clothing-Classification#2]
Hi,
I'm using fastai version 1.0.44. I wasn't able to install fastai version 1.0.24 because there isn't a corresponding version of torch-vision nightly for the package. I'm trying to load the export.pkl file using load_learner. But I got the following error.

"Invalid magic number; corrupt file?"

Can you please guide with this error?

**Comment by pankajarm** [comment]
Sorry for super delayed reply, Not sure how I missed this issue, but export.pkl will be your trained model exported file which you usually export by learner.save() in fastai version 1, this has changed in fastai version 2, please check latest fastai documentation for more details https://docs.fast.ai/
